### ISSUE TITLE
Logical Error

### ISSUE THREAD

**Issue by PascalNegwer** [spryker-eco/easycredit#10]
https://github.com/spryker-eco/easycredit/blob/089d8a798c56883b8c02d7b2b6568d6d26efe4eb/src/SprykerEco/Zed/Easycredit/Business/Payment/PaymentMethodFilter.php#L62

I guess it should be `$quoteTransfer->getBillingAddress()->getIso2Code()`

Also shouldn't it be only available if all of those three conditions are met?

**Comment by tvaleriy** [comment]
Hi @PascalNegwer,

thank you for the report.
Indeed looks like an issue.
I'll create an internal ticket for this.
Please use next time our official support portal - https://support.spryker.com/hc/en-us/requests/new. As we can easily miss such tickets in our repositories.

Best,
Spryker Support Team

**Comment by PascalNegwer** [comment]
Hi @tvaleriy all right i'll do so next time, thank you very much

**Comment by tvaleriy** [comment]
Hi @PascalNegwer, this should have been fixed in https://github.com/spryker-eco/easycredit/releases/tag/1.0.4.

Best,
Spryker Support Team
